### ISSUE TITLE
Error when regenerating tiles after diff updates

### ISSUE THREAD

**Issue by vitalcrazz** [osm2vectortiles/osm2vectortiles#475]
Hello!

I do diff updates with following commands:

```
docker-compose run update-osm-diff
docker-compose run import-osm-diff
docker-compose run merge-osm-diff
```

Then I want to generate tiles:

```
docker-compose run \
  -e BBOX="23.13,51.22,32.82,56.21" \
  -e MIN_ZOOM="6" \
  -e MAX_ZOOM="14" \
  export
```

And I get this error:

```
/usr/local/lib/node_modules/tilelive/bin/tilelive-copy:100
        if (err) throw err;
                 ^

Error: Postgis Plugin: ERROR:  relation "landuse_z13toz14" does not exist
LINE 1: SELECT ST_SRID("geometry") AS srid FROM landuse_z13toz14 WHE...
                                                ^
in executeQuery Full sql was: 'SELECT ST_SRID("geometry") AS srid FROM landuse_z13toz14 WHERE "geometry" IS NOT NULL LIMIT 1;'

    at Error (native)
    at /usr/local/lib/node_modules/tilelive-tmsource/index.js:111:18
    at Array.map (native)
    at normalize (/usr/local/lib/node_modules/tilelive-tmsource/index.js:100:35)
    at /usr/local/lib/node_modules/tilelive-tmsource/index.js:185:19
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

Manually it could be fixed with this commands in psql:

```
\i /path/to/osm2vectortiles/src/import-sql/layers/landuse.sql
\i /path/to/osm2vectortiles/src/import-sql/layers/landuse_overlay.sql
\i /path/to/osm2vectortiles/src/import-sql/layers/water_label.sql
```

But I can't understand why this views disappeared after the "diff updates" commands. Before executing this commands all the views were in database. I checked it.
This error occurs every time I do diff updates, not just once.

**Comment by mr** [comment]
I'd like to +1 this issue. I've been trying to do almost the exact same thing. I put a normal osmchange file in the import directory and just ran import-osm-diff. If there's more that I should do to pull in changes, please let me know and we can maybe write some documentation on it.
